if: branch =~ ^master|^development
language: php
group: stable
dist: trusty
os: linux
sudo: required
php:
  - 7.2.18

install:
  - pip install awscli --upgrade --user
  - composer install
  - php artisan key:generate --env=testing

script:
  - composer run-script phpunit
